#' Diagnosis Performed
#'
#' @param col A column in PTOS data that typically starts with 'icd9_'
#'
#' @return It translations of the code into human friendly values.
#' @export
diagnosis_lvl_1 <- function(col) {
  col_value <-  case.(col >= 1 & col  <= 139, 'Infectious And Parasitic Diseases',
                      col >= 140 & col  <= 239, 'Neoplasms',
                      col >= 240 & col  <= 279, 'Endocrine, Nutritional And Metabolic Diseases, And Immunity Disorders',
                      col >= 280 & col  <= 289, 'Diseases Of The Blood And Blood-Forming Organs',
                      col >= 290 & col  <= 319, 'Mental Disorders',
                      col >= 320 & col  <= 389, 'Diseases Of The Nervous System And Sense Organs',
                      col >= 390 & col  <= 459, 'Diseases Of The Circulatory System',
                      col >= 460 & col  <= 519, 'Diseases Of The Respiratory System',
                      col >= 520 & col  <= 579, 'Diseases Of The Digestive System',
                      col >= 580 & col  <= 629, 'Diseases Of The Genitourinary System',
                      col >= 630 & col  <= 679, 'Complications Of Pregnancy, Childbirth, And The Puerperium',
                      col >= 680 & col  <= 709, 'Diseases Of The Skin And Subcutaneous Tissue',
                      col >= 710 & col  <= 739, 'Diseases Of The Musculoskeletal System And Connective Tissue',
                      col >= 740 & col  <= 759, 'Congenital Anomalies',
                      col >= 760 & col  <= 779, 'Certain Conditions Originating In The Perinatal Period',
                      col >= 780 & col  <= 799, 'Symptoms, Signs, And Ill-Defined Conditions',
                      col >= 800 & col  <= 999, 'Injury And Poisoning',

                      default =   'Not Documented' )
  return(col_value)
}

#' @rdname diagnosis_lvl_1
#' @export

diagnosis_lvl_2 <- function(col) {
  col_value <-  case.(col >= 1 & col  <= 9, 'Intestinal Infectious Diseases',
                      col >= 10 & col  <= 18, 'Tuberculosis',
                      col >= 20 & col  <= 27, 'Zoonotic Bacterial Diseases',
                      col >= 30 & col  <= 41, 'Other Bacterial Diseases',
                      col >= 42 & col  <= 42, 'Human Immunodeficiency Virus (Hiv) Infection',
                      col >= 45 & col  <= 49, 'Poliomyelitis And Other Non-Arthropod-Borne Viral Diseases And Prion Diseases Of Central Nervous System',
                      col >= 50 & col  <= 59, 'Viral Diseases Generally Accompanied By Exanthem',
                      col >= 60 & col  <= 66, 'Arthropod-Borne Viral Diseases',
                      col >= 70 & col  <= 79, 'Other Diseases Due To Viruses And Chlamydiae',
                      col >= 80 & col  <= 88, 'Rickettsioses And Other Arthropod-Borne Diseases',
                      col >= 90 & col  <= 99, 'Syphilis And Other Venereal Diseases',
                      col >= 100 & col  <= 104, 'Other Spirochetal Diseases',
                      col >= 110 & col  <= 118, 'Mycoses',
                      col >= 120 & col  <= 129, 'Helminthiases',
                      col >= 130 & col  <= 136, 'Other Infectious And Parasitic Diseases',
                      col >= 137 & col  <= 139, 'Late Effects Of Infectious And Parasitic Diseases',
                      col >= 140 & col  <= 149, 'Malignant Neoplasm Of Lip, Oral Cavity, And Pharynx',
                      col >= 150 & col  <= 159, 'Malignant Neoplasm Of Digestive Organs And Peritoneum',
                      col >= 160 & col  <= 165, 'Malignant Neoplasm Of Respiratory And Intrathoracic Organs',
                      col >= 170 & col  <= 176, 'Malignant Neoplasm Of Bone, Connective Tissue, Skin, And Breast',
                      col >= 179 & col  <= 189, 'Malignant Neoplasm Of Genitourinary Organs',
                      col >= 190 & col  <= 199, 'Malignant Neoplasm Of Other And Unspecified Sites',
                      col >= 200 & col  <= 208, 'Malignant Neoplasm Of Lymphatic And Hematopoietic Tissue',
                      col >= 209 & col  <= 209, 'Neuroendocrine Tumors',
                      col >= 210 & col  <= 229, 'Benign Neoplasms',
                      col >= 230 & col  <= 234, 'Carcinoma In Situ',
                      col >= 235 & col  <= 238, 'Neoplasms Of Uncertain Behavior',
                      col >= 239 & col  <= 239, 'Neoplasms Of Unspecified Nature',
                      col >= 240 & col  <= 246, 'Disorders Of Thyroid Gland',
                      col >= 249 & col  <= 259, 'Diseases Of Other Endocrine Glands',
                      col >= 260 & col  <= 269, 'Nutritional Deficiencies',
                      col >= 270 & col  <= 279, 'Other Metabolic And Immunity Disorders',
                      col >= 290 & col  <= 299, 'Psychoses',
                      col >= 290 & col  <= 294, 'Organic Psychotic Conditions',
                      col >= 295 & col  <= 299, 'Other Psychoses',
                      col >= 300 & col  <= 316, 'Neurotic Disorders, Personality Disorders, And Other Nonpsychotic Mental Disorders',
                      col >= 317 & col  <= 319, 'Intellectual Disabilities',
                      col >= 320 & col  <= 326, 'Inflammatory Diseases Of The Central Nervous System',
                      col >= 327 & col  <= 327, 'Organic Sleep Disorders',
                      col >= 330 & col  <= 337, 'Hereditary And Degenerative Diseases Of The Central Nervous System',
                      col >= 338 & col  <= 338, 'Pain',
                      col >= 339 & col  <= 339, 'Other Headache Syndromes',
                      col >= 340 & col  <= 349, 'Other Disorders Of The Central Nervous System',
                      col >= 350 & col  <= 359, 'Disorders Of The Peripheral Nervous System',
                      col >= 360 & col  <= 379, 'Disorders Of The Eye And Adnexa',
                      col >= 380 & col  <= 389, 'Diseases Of The Ear And Mastoid Process',
                      col >= 390 & col  <= 392, 'Acute Rheumatic Fever',
                      col >= 393 & col  <= 398, 'Chronic Rheumatic Heart Disease',
                      col >= 401 & col  <= 405, 'Hypertensive Disease',
                      col >= 410 & col  <= 414, 'Ischemic Heart Disease',
                      col >= 415 & col  <= 417, 'Diseases Of Pulmonary Circulation',
                      col >= 420 & col  <= 429, 'Other Forms Of Heart Disease',
                      col >= 430 & col  <= 438, 'Cerebrovascular Disease',
                      col >= 440 & col  <= 449, 'Diseases Of Arteries, Arterioles, And Capillaries',
                      col >= 451 & col  <= 459, 'Diseases Of Veins And Lymphatics, And Other Diseases Of Circulatory System',
                      col >= 460 & col  <= 466, 'Acute Respiratory Infections',
                      col >= 470 & col  <= 478, 'Other Diseases Of The Upper Respiratory Tract',
                      col >= 480 & col  <= 488, 'Pneumonia And Influenza',
                      col >= 490 & col  <= 496, 'Chronic Obstructive Pulmonary Disease And Allied Conditions',
                      col >= 500 & col  <= 508, 'Pneumoconioses And Other Lung Diseases Due To External Agents',
                      col >= 510 & col  <= 519, 'Other Diseases Of Respiratory System',
                      col >= 520 & col  <= 529, 'Diseases Of Oral Cavity, Salivary Glands, And Jaws',
                      col >= 530 & col  <= 539, 'Diseases Of Esophagus, Stomach, And Duodenum',
                      col >= 540 & col  <= 543, 'Appendicitis',
                      col >= 550 & col  <= 553, 'Hernia Of Abdominal Cavity',
                      col >= 555 & col  <= 558, 'Noninfectious Enteritis And Colitis',
                      col >= 560 & col  <= 569, 'Other Diseases Of Intestines And Peritoneum',
                      col >= 570 & col  <= 579, 'Other Diseases Of Digestive System',
                      col >= 580 & col  <= 589, 'Nephritis, Nephrotic Syndrome, And Nephrosis',
                      col >= 590 & col  <= 599, 'Other Diseases Of Urinary System',
                      col >= 600 & col  <= 608, 'Diseases Of Male Genital Organs',
                      col >= 610 & col  <= 612, 'Disorders Of Breast',
                      col >= 614 & col  <= 616, 'Inflammatory Disease Of Female Pelvic Organs',
                      col >= 617 & col  <= 629, 'Other Disorders Of Female Genital Tract',
                      col >= 630 & col  <= 633, 'Ectopic And Molar Pregnancy',
                      col >= 634 & col  <= 639, 'Other Pregnancy With Abortive Outcome',
                      col >= 640 & col  <= 649, 'Complications Mainly Related To Pregnancy',
                      col >= 650 & col  <= 659, 'Normal Delivery, And Other Indications For Care In Pregnancy, Labor, And Delivery',
                      col >= 660 & col  <= 669, 'Complications Occurring Mainly In The Course Of Labor And Delivery',
                      col >= 670 & col  <= 677, 'Complications Of The Puerperium',
                      col >= 678 & col  <= 679, 'Other Maternal And Fetal Complications',
                      col >= 680 & col  <= 686, 'Infections Of Skin And Subcutaneous Tissue',
                      col >= 690 & col  <= 698, 'Other Inflammatory Conditions Of Skin And Subcutaneous Tissue',
                      col >= 700 & col  <= 709, 'Other Diseases Of Skin And Subcutaneous Tissue',
                      col >= 710 & col  <= 719, 'Arthropathies And Related Disorders',
                      col >= 720 & col  <= 724, 'Dorsopathies',
                      col >= 725 & col  <= 729, 'Rheumatism, Excluding The Back',
                      col >= 730 & col  <= 739, 'Osteopathies, Chondropathies, And Acquired Musculoskeletal Deformities',
                      col >= 760 & col  <= 763, 'Maternal Causes Of Perinatal Morbidity And Mortality',
                      col >= 764 & col  <= 779, 'Other Conditions Originating In The Perinatal Period',
                      col >= 780 & col  <= 789, 'Symptoms',
                      col >= 790 & col  <= 796, 'Nonspecific Abnormal Findings',
                      col >= 797 & col  <= 799, 'Ill-Defined And Unknown Causes Of Morbidity And Mortality',
                      col >= 800 & col  <= 829, 'Fractures',
                      col >= 800 & col  <= 804, 'Fracture Of Skull',
                      col >= 805 & col  <= 809, 'Fracture Of Neck And Trunk',
                      col >= 810 & col  <= 819, 'Fracture Of Upper Limb',
                      col >= 820 & col  <= 829, 'Fracture Of Lower Limb',
                      col >= 830 & col  <= 839, 'Dislocation',
                      col >= 840 & col  <= 848, 'Sprains And Strains Of Joints And Adjacent Muscles',
                      col >= 850 & col  <= 854, 'Intracranial Injury, Excluding Those With Skull Fracture',
                      col >= 860 & col  <= 869, 'Internal Injury Of Thorax, Abdomen, And Pelvis',
                      col >= 870 & col  <= 897, 'Open Wounds',
                      col >= 870 & col  <= 879, 'Open Wound Of Head, Neck, And Trunk',
                      col >= 880 & col  <= 887, 'Open Wound Of Upper Limb',
                      col >= 890 & col  <= 897, 'Open Wound Of Lower Limb',
                      col >= 900 & col  <= 904, 'Injury To Blood Vessels',
                      col >= 905 & col  <= 909, 'Late Effects Of Injuries, Poisonings, Toxic Effects, And Other External Causes',
                      col >= 910 & col  <= 919, 'Superficial Injury',
                      col >= 920 & col  <= 924, 'Contusion With Intact Skin Surface',
                      col >= 925 & col  <= 929, 'Crushing Injury',
                      col >= 930 & col  <= 939, 'Effects Of Foreign Body Entering Through Orifice',
                      col >= 940 & col  <= 949, 'Burns',
                      col >= 950 & col  <= 957, 'Injury To Nerves And Spinal Cord',
                      col >= 958 & col  <= 959, 'Certain Traumatic Complications And Unspecified Injuries',
                      col >= 960 & col  <= 979, 'Poisoning By Drugs, Medicinal And Biological Substances',
                      col >= 980 & col  <= 989, 'Toxic Effects Of Substances Chiefly Nonmedicinal As To Source',
                      col >= 990 & col  <= 995, 'Other And Unspecified Effects Of External Causes',
                      col >= 996 & col  <= 999, 'Complications Of Surgical And Medical Care, Not Elsewhere Classified',
                      default =   'Not Documented' )
  return(col_value)
}

#' @rdname diagnosis_lvl_2
#' @export
