#' Activity Code for Injury
#'
#' @param col A column in PTOS data that typically starts with E_ACT_1
#'
#' @return It translations of the code into human friendly values.
#' @export
#'
#' @examples
ecode_act <- function(col) {
  col_value <-  case.(col == 001.0,    'Activities involving walking, marching and hiking',
                      col == 001.1,    'Activities involving running',
                      col == 002.0,    'Activities involving swimming',
                      col == 002.1,    'Activities involving springboard and platform diving',
                      col == 002.2,    'Activities involving water polo',
                      col == 002.3,    'Activities involving water aerobics and water exercise',
                      col == 002.4,    'Activities involving underwater diving and snorkeling',
                      col == 002.5,    'Activities involving rowing, canoeing, kayaking, rafting and tubing',
                      col == 002.6,    'Activities involving water skiing and wake boarding',
                      col == 002.7,    'Activities involving surfing, windsurfing and boogie boarding',
                      col == 002.8,    'Activities involving water sliding',
                      col == 002.9,    'Other activity involving water and watercraft',
                      col == 003.0,    'Activities involving ice skating',
                      col == 003.1,    'Activities involving ice hockey',
                      col == 003.2,    'Activities w/ snow skiing/snowboarding/sledding/tobogganing & snow tubing',
                      col == 003.3,    'Activities involving cross country skiing',
                      col == 003.9,    'Other activity involving ice and snow',
                      col == 004.0,    'Activities involving mountain climbing, rock climbing and wall climbing',
                      col == 004.1,    'Activities involving rappelling',
                      col == 004.2,    'Activities involving BASE jumping',
                      col == 004.3,    'Activities involving bungee jumping',
                      col == 004.4,    'Activities involving hang gliding',
                      col == 004.9,    'Other activity involving climbing, rappelling and jumping off',
                      col == 005.0,    'Activities involving dancing',
                      col == 005.1,    'Activities involving yoga',
                      col == 005.2,    'Activities involving gymnastics',
                      col == 005.3,    'Activities involving trampoline',
                      col == 005.4,    'Activities involving cheerleading',
                      col == 005.9,    'Other activity involving dancing and other rhythmic movements',
                      col == 006.0,    'Activities involving roller skating (inline) and skateboarding',
                      col == 006.1,    'Activities involving horseback riding',
                      col == 006.2,    'Activities involving golf',
                      col == 006.3,    'Activities involving bowling',
                      col == 006.4,    'Activities involving bike riding',
                      col == 006.5,    'Activities involving jumping rope',
                      col == 006.6,    'Activities involving non-running track and field events',
                      col == 006.9,    'Other activity involving other sports and athletics played individually',
                      col == 007.0,    'Activities involving american tackle football',
                      col == 007.1,    'Activities involving american flag or touch football',
                      col == 007.2,    'Activities involving rugby',
                      col == 007.3,    'Activities involving baseball',
                      col == 007.4,    'Activities involving lacrosse and field hockey',
                      col == 007.5,    'Activities involving soccer',
                      col == 007.6,    'Activities involving basketball',
                      col == 007.7,    'Activities involving volleyball (beach) (court)',
                      col == 007.8,    'Activities involving physical games during school recess and summer camp',
                      col == 007.9,    'Other activity involving other sports and athletes played as a team',
                      col == 008.0,    'Activities involving boxing',
                      col == 008.1,    'Activities involving wrestling',
                      col == 008.2,    'Activities involving racquet and hand sports',
                      col == 008.3,    'Activities involving frisbee',
                      col == 008.4,    'Activities involving martial arts',
                      col == 008.9,    'Other specified sports and athletics activity',
                      col == 009.0,    'Activity involving exercise machines primarily for areobic conditioning',
                      col == 009.1,    'Activity involving calisthenics',
                      col == 009.2,    'Activity involving aerobic and step exercise',
                      col == 009.3,    'Activity involving circuit training',
                      col == 009.4,    'Activity involving obstacle course',
                      col == 009.5,    'Activity involving grass drills',
                      col == 009.9,    'Other activity involving cardiorespiratory exercise',
                      col == 010.0,    'Activity involving exercise machines primarily for muscle strengthening',
                      col == 010.1,    'Activity involving push-ups, pull-ups, sit-ups',
                      col == 010.2,    'Activity involving free weights',
                      col == 010.3,    'Activity involving pilates',
                      col == 010.9,    'Other activity involving other muscle strengthening exercises',
                      col == 011.0,    'Activities involving computer keyboarding',
                      col == 011.1,    'Activities involving hand held interactive electronic device',
                      col == 011.9,    'Other activity involving computer technology and electronic devices',
                      col == 012.0,    'Activities involving knitting and crocheting',
                      col == 012.1,    'Activities involving sewing',
                      col == 012.2,    'Activities involving furniture building and finishing',
                      col == 012.9,    'Activity involving other arts and handcrafts',
                      col == 013.0,    'Activities involving personal bathing and showering',
                      col == 013.1,    'Activities involving laundry',
                      col == 013.2,    'Activities involving vacuuming',
                      col == 013.3,    'Activities involving ironing',
                      col == 013.4,    'Activities involving floor mopping and cleaning',
                      col == 013.5,    'Activities involving residential relocation',
                      col == 013.8,    'Other personal hygiene activity',
                      col == 013.9,    'Other household maintenance',
                      col == 014.0,    'Caregiving involving bathing',
                      col == 014.1,    'Caregiving involving lifting',
                      col == 014.9,    'Other activity involving person providing caregiving',
                      col == 015.0,    'Activities involving food preparation and clean up',
                      col == 015.1,    'Activities involving grilling and smoking food',
                      col == 015.2,    'Activities involving cooking and baking',
                      col == 015.9,    'Other activity involving cooking and grilling',
                      col == 016.0,    'Activities involving digging, shoveling and raking',
                      col == 016.1,    'Activities involving gardening and landscaping',
                      col == 016.2,    'Activities involving building and construction',
                      col == 016.9,    'Other activity with property/land maintenance/building & construction',
                      col == 017.0,    'Roller coaster riding',
                      col == 017.9,    'Other activity involving external motion',
                      col == 018.0,    'Activities involving piano playing',
                      col == 018.1,    'Activities involving drum and other percussion instrument playing',
                      col == 018.2,    'Activities involving string instrument playing',
                      col == 018.3,    'Activities involving winds and brass instrument playing',
                      col == 019.0,    'Activities involving walking an animal',
                      col == 019.1,    'Activities involving milking an animal',
                      col == 019.2,    'Activities involving grooming and shearing an animal',
                      col == 019.9,    'Other activity involving animal care',
                      col == 029.0,    'Refereeing a sports activity',
                      col == 029.1,    'Spectator at an event',
                      col == 029.2,    'Rough housing and horseplay',
                      col == 029.9,    'Other activity',
                      col == 030,    'Unspecified activity',
                      default = "Unknown")
  return(col_value)
}
