#' Procedures Performed
#' Record both operative and non-operative procedures performed in your facility
#'
#' @param col A column in PTOS data that typically ends in _PR.
#'
#' @return It translations of the code into human friendly values.
#' @export
procedure_lvl_1 <- function(col) {
  col_value <-  case.(col >= 00.01 & col  <= 0.96, 'PROCEDURES AND INTERVENTIONS , NOT ELSEWHERE CLASSIFIED (00)',
                      col >= 1.01 & col  <= 5.9, 'OPERATIONS ON THE NERVOUS SYSTEM (01-05)',
                      col >= 6.01 & col  <= 7.99, 'OPERATIONS ON THE ENDOCRINE SYSTEM (06-07)',
                      col >= 8.01 & col  <= 16.99, 'OPERATIONS ON THE EYE (08-16)',
                      col >= 17.11 & col  <= 17.81, 'OTHER MISCELLANEOUS DIAGNOSTIC AND THERAPEUTIC PROCEDURES (17)',
                      col >= 18.01 & col  <= 20.99, 'OPERATIONS ON THE EAR (18-20)',
                      col >= 21 & col  <= 29.99, 'OPERATIONS ON THE NOSE, MOUTH, AND PHARYNX (21-29)',
                      col >= 30.01 & col  <= 34.99, 'OPERATIONS ON THE RESPIRATORY SYSTEM (30-34)',
                      col >= 35 & col  <= 39.99, 'OPERATIONS ON THE CARDIOVASCULAR SYSTEM (35-39)',
                      col >= 40 & col  <= 41.99, 'OPERATIONS ON THE HEMIC AND LYMPHATIC SYSTEM (40-41)',
                      col >= 42.01 & col  <= 54.99, 'OPERATIONS ON THE DIGESTIVE SYSTEM (42-54)',
                      col >= 55.01 & col  <= 59.99, 'OPERATIONS ON THE URINARY SYSTEM (55-59)',
                      col >= 60 & col  <= 64.99, 'OPERATIONS ON THE MALE GENITAL ORGANS (60-64)',
                      col >= 65.01 & col  <= 71.9, 'OPERATIONS ON THE FEMALE GENITAL ORGANS (65-71)',
                      col >= 72 & col  <= 75.99, 'OBSTETRICAL PROCEDURES (72-75)',
                      col >= 76.01 & col  <= 84.99, 'OPERATIONS ON THE MUSCULOSKELETAL SYSTEM (76-84)',
                      col >= 85 & col  <= 86.99, 'OPERATIONS ON THE INTEGUMENTARY SYSTEM (85-86)',
                      col >= 87.01 & col  <= 99.99, 'MISCELLANEOUS DIAGNOSTIC AND THERAPEUTIC PROCEDURES (87-99)',
                      default =   'Not Documented' )
  return(col_value)
}

#' @rdname procedure_lvl_1
#' @export
procedure_lvl_2 <- function(col) {
  col_value <-  case.(col >= 0.01 & col  <= 00.09  , 'Therapeutic ultrasound',
                      col >= 0.1 & col  <= 00.19  , 'Pharamaceuticals',
                      col >= 0.21 & col  <= 00.29  , 'Intravascular imaging of blood vessels',
                      col >= 0.31 & col  <= 00.39  , 'Computer assisted surgery [CAS]',
                      col >= 0.4 & col  <= 00.49  , 'Adjunct Vascular System Procedures',
                      col >= 0.5 & col  <= 00.59  , 'Other cardiovascular procedures',
                      col >= 0.6 & col  <= 00.69  , 'Procedures on blood vessels',
                      col >= 0.7 & col  <= 00.77  , 'Other hip procedures',
                      col >= 0.8 & col  <= 00.87  , 'Other knee and hip procedures',
                      col >= 0.91 & col  <= 00.96  , 'Other procedures and interventions',
                      col >= 1.01 & col  <= 1.6, 'Incision and excision of skull, brain, and cerebral meninges',
                      col >= 2.01 & col  <= 2.99, 'Other operations on skull, brain, and cerebral meninges',
                      col >= 3.01 & col  <= 3.99, 'Operations on spinal cord and spinal canal structures',
                      col >= 4.01 & col  <= 4.99, 'Operations on cranial and peripheral nerves',
                      col >= 5 & col  <= 5.9, 'Operations on sympathetic nerves or ganglia',
                      col >= 6.01 & col  <= 6.99, 'Operations on thyroid and parathyroid glands',
                      col >= 7 & col  <= 7.99, 'Operations on other endocrine glands',
                      col >= 8.01 & col  <= 8.99, 'Operations on eyelids',
                      col >= 9 & col  <= 9.99, 'Operations on lacrimal system',
                      col >= 10 & col  <= 10.99, 'Operations on conjunctiva',
                      col >= 11 & col  <= 11.99, 'Operations on cornea',
                      col >= 12 & col  <= 12.99, 'Operations on iris, ciliary body, sclera, and anterior chamber',
                      col >= 13 & col  <= 13.91, 'Operations on lens',
                      col >= 14 & col  <= 14.9, 'Operations on retina, choroid, vitreous, and posterior chamber',
                      col >= 15.01 & col  <= 15.9, 'Operations on extraocular muscles',
                      col >= 16.01 & col  <= 16.99, 'Operations on orbit and eyeball',
                      col >= 17.11 & col  <= 17.81, 'Other miscellaneous procedures',
                      col >= 18.01 & col  <= 18.9, 'Operations on external ear',
                      col >= 19 & col  <= 19.9, 'Reconstructive operations on middle ear',
                      col >= 20.01 & col  <= 20.99, 'Other operations on middle and inner ear',
                      col >= 21 & col  <= 21.99, 'Operations on nose',
                      col >= 22 & col  <= 22.9, 'Operations on nasal sinuses',
                      col >= 23.01 & col  <= 23.73, 'Removal and restoration of teeth',
                      col >= 24 & col  <= 24.99, 'Other operations on teeth, gums, and alveoli',
                      col >= 25.01 & col  <= 25.99, 'Operations on tongue',
                      col >= 26 & col  <= 26.99, 'Operations on salivary glands and ducts',
                      col >= 27 & col  <= 27.99, 'Other operations on mouth and face',
                      col >= 28 & col  <= 28.99, 'Operations on tonsils and adenoids',
                      col >= 29 & col  <= 29.99, 'Operations on pharynx',
                      col >= 30.01 & col  <= 30.4, 'Excision of larynx',
                      col >= 31 & col  <= 31.99, 'Other operations on larynx and trachea',
                      col >= 32.01 & col  <= 32.9, 'Excision of lung and bronchus',
                      col >= 33 & col  <= 33.99, 'Other operations on lung and bronchus',
                      col >= 34.01 & col  <= 34.99, 'Operations on chest wall, pleura, mediastinum, and diaphragm',
                      col >= 35 & col  <= 35.99, 'Operations on valves and septa of heart',
                      col >= 36.03 & col  <= 36.99, 'Operations on vessels of heart',
                      col >= 37 & col  <= 37.99, 'Other operations on heart and pericardium',
                      col >= 38 & col  <= 38.99, 'Incision, excision, and occlusion of vessels',
                      col >= 39 & col  <= 39.99, 'Other operations on vessels',
                      col >= 40 & col  <= 40.9, 'Operations on lymphatic system',
                      col >= 41 & col  <= 41.99, 'Operations on bone marrow and spleen',
                      col >= 42.01 & col  <= 42.99, 'Operations on esophagus',
                      col >= 43 & col  <= 43.99, 'Incision and excision of stomach',
                      col >= 44 & col  <= 44.99, 'Other operations on stomach',
                      col >= 45 & col  <= 45.95, 'Incision, excision, and anastomosis of intestine',
                      col >= 46.01 & col  <= 46.99, 'Other operations on intestine',
                      col >= 47.01 & col  <= 47.99, 'Operations on appendix',
                      col >= 48 & col  <= 48.99, 'Operations on rectum, rectosigmoid and perirectal tissue',
                      col >= 49.01 & col  <= 49.99, 'Operations on anus',
                      col >= 50 & col  <= 50.99, 'Operations on liver',
                      col >= 51.01 & col  <= 51.99, 'Operations on gallbladder and biliary tract',
                      col >= 52.01 & col  <= 52.99, 'Operations on pancreas',
                      col >= 53 & col  <= 53.9, 'Repair of hernia',
                      col >= 54 & col  <= 54.99, 'Other operations on abdominal region',
                      col >= 55.01 & col  <= 55.99, 'Operations on kidney',
                      col >= 56 & col  <= 56.99, 'Operations on ureter',
                      col >= 57 & col  <= 57.99, 'Operations on urinary bladder',
                      col >= 58 & col  <= 58.99, 'Operations on urethra',
                      col >= 59 & col  <= 59.99, 'Other operations on urinary tract',
                      col >= 60 & col  <= 60.99, 'Operations on prostate and seminal vesicles',
                      col >= 61 & col  <= 61.99, 'Operations on scrotum and tunica vaginalis',
                      col >= 62 & col  <= 62.99, 'Operations on testes',
                      col >= 63.01 & col  <= 63.99, 'Operations on spermatic cord, epididymis, and vas deferens',
                      col >= 64 & col  <= 64.99, 'Operations on penis',
                      col >= 65.01 & col  <= 65.99, 'Operations on ovary',
                      col >= 66.01 & col  <= 66.99, 'Operations on fallopian tubes',
                      col >= 67 & col  <= 67.69, 'Operations on cervix',
                      col >= 68 & col  <= 68.9, 'Other incision and excision of uterus',
                      col >= 69.01 & col  <= 69.99, 'Other operations on uterus and supporting structures',
                      col >= 70 & col  <= 70.95, 'Operations on vagina and cul-de-sac',
                      col >= 71.01 & col  <= 71.9, 'Operations on vulva and perineum',
                      col >= 72 & col  <= 72.9, 'Forceps, vacuum, and breech delivery',
                      col >= 73.01 & col  <= 73.99, 'Other procedures inducing or assisting delivery',
                      col >= 74 & col  <= 74.99, 'Cesarean section and removal of fetus',
                      col >= 75 & col  <= 75.99, 'Other obstetric operations',
                      col >= 76.01 & col  <= 76.99, 'Operations on facial bones and joints',
                      col >= 77 & col  <= 77.99, 'Incision, excision, and division of other bones',
                      col >= 78 & col  <= 78.99, 'Other operations on bones, except facial bones',
                      col >= 79 & col  <= 79.99, 'Reduction of fracture and dislocation',
                      col >= 80 & col  <= 80.99, 'Incision and excision of joint structures',
                      col >= 81 & col  <= 81.99, 'Repair and plastic operations on joint structures',
                      col >= 82.01 & col  <= 82.99, 'Operations on muscle, tendon, and fascia of hand',
                      col >= 83.01 & col  <= 83.99, 'Operations on muscle, tendon, fascia, and bursa, except hand',
                      col >= 84 & col  <= 84.99, 'Other procedures on musculoskeletal system',
                      col >= 85 & col  <= 85.99, 'Operations on the breast',
                      col >= 86.01 & col  <= 86.99, 'Operations on skin and subcutaneous tissue',
                      col >= 87.01 & col  <= 87.99, 'Diagnostic Radiology',
                      col >= 88.01 & col  <= 88.98, 'Other diagnostic radiology and related techniques',
                      col >= 89.01 & col  <= 89.8, 'Interview, evaluation, consultation, and examination',
                      col >= 90.01 & col  <= 90.99, 'Microscopic examination-I',
                      col >= 91.01 & col  <= 91.99, 'Microscopic examination-II',
                      col >= 92.01 & col  <= 92.41, 'Nuclear medicine',
                      col >= 93.01 & col  <= 93.99, 'Physical therapy, respiratory therapy, rehabilitation, and related procedures',
                      col >= 94.01 & col  <= 94.69, 'Procedures related to the psyche',
                      col >= 95.01 & col  <= 95.49, 'Ophthalmologic and otologic diagnosis and treatment',
                      col >= 96.01 & col  <= 96.72, 'Nonoperative intubation and irrigation',
                      col >= 97.01 & col  <= 97.89, 'Replacement and removal of therapeutic appliances',
                      col >= 98.01 & col  <= 98.59, 'Nonoperative removal of foreign body or calculus',
                      col >= 99 & col  <= 99.99, 'Other nonoperative procedures',
                      default =   'Not Documented' )
  return(col_value)
}

#' @export
#' @rdname procedure_lvl_2
